### ISSUE TITLE
SWIFT-1039 ⁃ is this code work with mongodb realm?

### ISSUE THREAD

**Issue by yogendra-leocan** [mongodb/mongo-swift-driver#559] opened 2020-12-24 05:33 UTC
My mongodb is in realm, so this syntax work for me?

Please reply me as soon as possible.

**Comment by agolin95** [comment] 2021-01-04 19:40
Closing this as a duplicate of https://github.com/mongodb/mongo-swift-driver/issues/558, responding in 558.

**Closed by agolin95** 2021-01-04 19:40 UTC
