### ISSUE TITLE
WARNING: mongoc: Unknown rpc type: 0x00000000

### ISSUE THREAD

**Issue by danieleftodi** [mongodb/mongo-swift-driver#352] opened 2019-11-23 18:13 UTC
## Information
Running Vapor Server Side Swift (latest) with (latest) mongo-swift-driver

### Swift version
```
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin18.7.0
```
### Operating system
```
Darwin local.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin
```

### Driver version
```
{
  "object": {
    "pins": [
      {
        "package": "Console",
        "repositoryURL": "https://github.com/vapor/console.git",
        "state": {
          "branch": null,
          "revision": "74cfbea629d4aac34a97cead2447a6870af1950b",
          "version": "3.1.1"
        }
      },
      {
        "package": "Core",
        "repositoryURL": "https://github.com/vapor/core.git",
        "state": {
          "branch": null,
          "revision": "18f2436bf7a6bc2224372c0885db2e0159af1649",
          "version": "3.9.2"
        }
      },
      {
        "package": "Crypto",
        "repositoryURL": "https://github.com/vapor/crypto.git",
        "state": {
          "branch": null,
          "revision": "df8eb7d8ae51787b3a0628aa3975e67666da936c",
          "version": "3.3.3"
        }
      },
      {
        "package": "CwlCatchException",
        "repositoryURL": "https://github.com/mattgallagher/CwlCatchException.git",
        "state": {
          "branch": null,
          "revision": "7cd2f8cacc4d22f21bc0b2309c3b18acf7957b66",
          "version": "1.2.0"
        }
      },
      {
        "package": "CwlPreconditionTesting",
        "repositoryURL": "https://github.com/mattgallagher/CwlPreconditionTesting.git",
        "state": {
          "branch": null,
          "revision": "c228db5d2ad1b01ebc84435e823e6cca4e3db98b",
          "version": "1.2.0"
        }
      },
      {
        "package": "DatabaseKit",
        "repositoryURL": "https://github.com/vapor/database-kit.git",
        "state": {
          "branch": null,
          "revision": "8f352c8e66dab301ab9bfef912a01ce1361ba1e4",
          "version": "1.3.3"
        }
      },
      {
        "package": "Fluent",
        "repositoryURL": "https://github.com/vapor/fluent.git",
        "state": {
          "branch": null,
          "revision": "783819d8838d15e1a05b459aa0fd1bde1e37ac26",
          "version": "3.2.1"
        }
      },
      {
        "package": "FluentSQLite",
        "repositoryURL": "https://github.com/vapor/fluent-sqlite.git",
        "state": {
          "branch": null,
          "revision": "c32f5bda84bf4ea691d19afe183d40044f579e11",
          "version": "3.0.0"
        }
      },
      {
        "package": "HTTP",
        "repositoryURL": "https://github.com/vapor/http.git",
        "state": {
          "branch": null,
          "revision": "3808ed0401379b6e9f4a053f03090ea9d658caa9",
          "version": "3.2.1"
        }
      },
      {
        "package": "Leaf",
        "repositoryURL": "https://github.com/vapor/leaf.git",
        "state": {
          "branch": null,
          "revision": "d35f54cbac723e673f9bd5078361eea74049c8d7",
          "version": "3.0.2"
        }
      },
      {
        "package": "MongoSwift",
        "repositoryURL": "https://github.com/mongodb/mongo-swift-driver.git",
        "state": {
          "branch": null,
          "revision": "dd26fc7e4dda121626c64e0205fba75bd435db23",
          "version": "0.1.3"
        }
      },
      {
        "package": "Multipart",
        "repositoryURL": "https://github.com/vapor/multipart.git",
        "state": {
          "branch": null,
          "revision": "f063180d0b84832accd33194e06ed3c41f8609ac",
          "version": "3.1.1"
        }
      },
      {
        "package": "Nimble",
        "repositoryURL": "https://github.com/Quick/Nimble.git",
        "state": {
          "branch": null,
          "revision": "6abeb3f5c03beba2b9e4dbe20886e773b5b629b6",
          "version": "8.0.4"
        }
      },
      {
        "package": "Routing",
        "repositoryURL": "https://github.com/vapor/routing.git",
        "state": {
          "branch": null,
          "revision": "d76f339c9716785e5079af9d7075d28ff7da3d92",
          "version": "3.1.0"
        }
      },
      {
        "package": "Service",
        "repositoryURL": "https://github.com/vapor/service.git",
        "state": {
          "branch": null,
          "revision": "fa5b5de62bd68bcde9a69933f31319e46c7275fb",
          "version": "1.0.2"
        }
      },
      {
        "package": "SQL",
        "repositoryURL": "https://github.com/vapor/sql.git",
        "state": {
          "branch": null,
          "revision": "50eaeb8f52a1ce63f1ff3880e1114dd8757a78a6",
          "version": "2.3.2"
        }
      },
      {
        "package": "SQLite",
        "repositoryURL": "https://github.com/vapor/sqlite.git",
        "state": {
          "branch": null,
          "revision": "314d9cd21165bcf14215e336a23ff8214f40e411",
          "version": "3.2.1"
        }
      },
      {
        "package": "bson",
        "repositoryURL": "https://github.com/mongodb/swift-bson",
        "state": {
          "branch": null,
          "revision": "40f770ed265bb9958edbcd0c809a3c2afe75a3ba",
          "version": "2.1.0"
        }
      },
      {
        "package": "mongoc",
        "repositoryURL": "https://github.com/mongodb/swift-mongoc",
        "state": {
          "branch": null,
          "revision": "e503b50210dae2cf0220474c2f12087830150e9f",
          "version": "2.0.0"
        }
      },
      {
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio.git",
        "state": {
          "branch": null,
          "revision": "ba7970fe396e8198b84c6c1b44b38a1d4e2eb6bd",
          "version": "1.14.1"
        }
      },
      {
        "package": "swift-nio-ssl",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl.git",
        "state": {
          "branch": null,
          "revision": "0f3999f3e3c359cc74480c292644c3419e44a12f",
          "version": "1.4.0"
        }
      },
      {
        "package": "swift-nio-ssl-support",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl-support.git",
        "state": {
          "branch": null,
          "revision": "c02eec4e0e6d351cd092938cf44195a8e669f555",
          "version": "1.0.0"
        }
      },
      {
        "package": "swift-nio-zlib-support",
        "repositoryURL": "https://github.com/apple/swift-nio-zlib-support.git",
        "state": {
          "branch": null,
          "revision": "37760e9a52030bb9011972c5213c3350fa9d41fd",
          "version": "1.0.0"
        }
      },
      {
        "package": "TemplateKit",
        "repositoryURL": "https://github.com/vapor/template-kit.git",
        "state": {
          "branch": null,
          "revision": "51405c83e95e8adb09565278a5e9b959c605e56c",
          "version": "1.4.0"
        }
      },
      {
        "package": "URLEncodedForm",
        "repositoryURL": "https://github.com/vapor/url-encoded-form.git",
        "state": {
          "branch": null,
          "revision": "82d8d63bdb76b6dd8febe916c639ab8608dbbaed",
          "version": "1.0.6"
        }
      },
      {
        "package": "Validation",
        "repositoryURL": "https://github.com/vapor/validation.git",
        "state": {
          "branch": null,
          "revision": "4de213cf319b694e4ce19e5339592601d4dd3ff6",
          "version": "2.1.1"
        }
      },
      {
        "package": "Vapor",
        "repositoryURL": "https://github.com/vapor/vapor.git",
        "state": {
          "branch": null,
          "revision": "92a58a9a84e4330500b99fe355a94d29f67abe58",
          "version": "3.3.1"
        }
      },
      {
        "package": "WebSocket",
        "repositoryURL": "https://github.com/vapor/websocket.git",
        "state": {
          "branch": null,
          "revision": "d85e5b6dce4d04065865f77385fc3324f98178f6",
          "version": "1.1.2"
        }
      }
    ]
  },
  "version": 1
}
```

### What is the version(s) of `mongod` that you are running with the driver?
```
db version v4.2.1
git version: edf6d45851c0b9ee15548f0f847df141764a317e
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

### What is your server topology?
How is your MongoDB deployment configured?
```
Nothing special, just standard. Just a simple CRUD implementation with Vapor for an iOS App we use to get / update the data in our MongoDB ...
```

### How did you install `libmongoc` and `libbson` on your system
Used Brew ...

### Version of libmongoc and libbson
```
mongo-c-driver 1.15.1
```

## What is the problem? 

The implementation works, but sometimes ... after a few fetches from our iOS App, we get this warning (in the console):
```
WARNING:       mongoc: Unknown rpc type: 0x00000000
```

and the following error message in Xcode:
```
NIO-ELT-#1 (5): signal SIGABRT
```
<a href="https://i.ibb.co/zr4cbt6/Screenshot-2019-11-23-at-18-51-24.png"><img src="https://i.ibb.co/6mWhbqX/Screenshot-2019-11-23-at-18-51-24.png" alt="Screenshot-2019-11-23-at-18-51-24" border="0"></a>

## Reproducing the bug

1. Run Vapor app
2. Load a few time from our iOS App ...
3. And sometimes, after a while ..
4. We get the warning

**Comment by kmahar** [comment] 2019-11-25 17:10
Hi @danieleftodi! Thanks for reaching out.

My first guess would be that this is due to accessing some non-thread-safe types across multiple threads at once. Is it possible that you are sharing a `MongoClient` or `MongoCursor` across threads?

We've done work since the last release to make `MongoClient` thread-safe, but we have not released it yet.

If the thread safety issue is indeed the problem, I have a few possible suggestions for ways you might be able to work around this for now.

**Comment by kmahar** [comment] 2019-11-25 17:33
If it is indeed the multithreading issue:

One option is to rewrite your application to not use clients across threads. However, given that our next release would make that change obsolete, it may not be worth your time to do that work only to change it later.

Another option would be to pin to a more recent revision of the driver, where clients are safe to be used across threads and will automatically pool connections to the server.

The reason we haven't released this code yet is because in the process of implementing the connection pooling in Swift we found a bug in libmongoc involving using connection pooling + SSL (on MacOS only, works fine on Ubuntu 18.04), and they have not released the fix for it yet. So if you pin to a more recent revision of the driver and you are using SSL you could run into this issue on MacOS.
If you are not using SSL on MacOS, then you should be fine to pin to a more recent revision.

One thing to note is that we changed the BSON API pretty significantly since the last release. Depending on how much you are working with `Document`s it may take a bit of work to switch to the new API. If you don't want to deal with that now you could pin to the commit before the API changed: e3dee070808b1b764774468fb9198067ba467d99
If you do want to incorporate the new BSON API now you can pin to something more recent (e.g. f8b474dbc6bb0c53059f42fe8f11c7aa4038a802) and use this [guide](https://github.com/mongodb/mongo-swift-driver/blob/master/Guides/BSON.md#migrating-from-the-old-bson-api) for advice on migrating.

**Comment by danieleftodi** [comment] 2019-12-17 05:14
Hi @kmahar,

I've move the swift vapor server from macOS --> Ubuntu. And done a lot of test & stress tests. And it still crashes with the same error:

 `WARNING: mongoc: Unknown rpc type: 0x00000000`

And I have found a lot of other errors that also occur. 
Please find the "[Backend_Server_Crash.log](https://www.dropbox.com/s/e9j4y3mp9sdrudf/Backend_Server_Crash.log?dl=0)"-file of them in this link. 

Regarding the Server-side Swift code in Vapor that causes the crash:
```
router.get("dev") { req -> [DEV_INF] in
     let console = try req.make(Console.self)
     console.print("GET :: dev :: ", newLine: false)
     console.output("@", style: .init(color: .yellow), newLine: false)
     console.output(String((Date().timeIntervalSince1970 * 1000)), style: .init(color: .cyan), newLine: true)
     let client = try! req.make(MongoClient.self)
     let collection = client.db("dev_app").collection("dev_coll", withType: DEV_INF.self)
     let cursor = try! collection.find()
     return Array(cursor)
}
```

I have used [Modern HTTP benchmarking tool](https://github.com/wg/wrk) to stress test the server:
`wrk -c 1 -d 60m -t 1 --latency --timeout 10 http://localhost.local:8080/dev`

And I have found out that if I use `-c 1` and `-t 1` .... I can run the stress test without a glitch.

But if I increase to two connections `-c 2` and one thread `-t 1` ... I'll get it to crash 100% of the time.

One of the last things I'm testning now is to run the "Backend Server" behind Nginx 👍🏻 ... and it looks to be working better in "Real World Use" ... with our iOS App that is fetching the data ..., but I can still get it to crash 100% of the time too, when I use the `wrk` benchmarking tool. (the iOS App is just prolonging the ineverable crash from happening, but it too crashes).

**Comment by kmahar** [comment] 2019-12-17 05:30
It looks like you have registered `MongoClient` as a service in your Vapor app; can you please post a code snippet showing how you are doing that? 
I am wondering if it is possible that the same `MongoClient` instance is being returned each time you call `req.make(MongoClient.self)`.

**Comment by danieleftodi** [comment] 2019-12-17 05:54
**configure.swift**
```
import Vapor
import MongoSwift

/// Called before your application initializes.
public func configure(_ config: inout Config, _ env: inout Environment, _ services: inout Services) throws {
    let mongoclient = try MongoClient("mongodb://localhost:27017")
    let mongodb = mongoclient.db("vaporapp")
    do {
      _ = try mongodb.createCollection("users")
    } catch {
      _ = mongodb.collection("users")
    }
    services.register(mongoclient)
    
    let mongoclient_dev = try MongoClient("mongodb://localhost:27017")
    let mongodb_dev = mongoclient_bit_dev.db("dev_app")
    do {
      _ = try mongodb_dev.createCollection("dev_coll")
    } catch {
      _ = mongodb_dev.collection("dev_coll")
    }
    services.register(mongoclient_dev)
}
extension MongoClient: Service {}
```

**Comment by danieleftodi** [comment] 2019-12-17 05:57
@kmahar 

I followed these guides:
https://medium.com/@volodymyrklymenko/server-side-swift-how-to-use-vapor-3-with-mongodb-baf9b79c8d0
https://medium.com/@Soulfected/vapor-3-with-mongo-db-ea2e59347dd6

**Comment by danieleftodi** [comment] 2019-12-17 06:23
> I am wondering if it is possible that the same `MongoClient` instance is being returned each time you call `req.make(MongoClient.self)`.

From my newbie understanding of Vapor 3, is that Vapor 3 spins of a async process for each new Route-request being requested (with all it's dependencies). Meaning Request-A and B are living their own lives until they complete their task. 

I don't know how MongoDB handles issues if multiple READ Requests (say: A & B) are simultaneously asking for a Read from the db (lim --> 0)? 

Also, how does MongoDB handle if different types of requests, READ and WRITE, are incoming simultaneously (Say: A & B are READ ... and C is Write ... when lim --> 0

**Comment by kmahar** [comment] 2019-12-18 22:04
Hi @danieleftodi, I've tested this locally and confirmed that my suspicion above is true. Since you register a particular `MongoClient` instance as a service, that same client object is being returned every time you call `req.make(MongoClient.self)`.

This means that when there are two concurrent requests made they can run into race conditions attempting to use the same client.

Two options for you:
1) Update to MongoSwift 0.2.0 (released earlier today) and see if you still have the problem. As of that release the client is safe to share across threads / use for concurrent requests, and in fact we encourage sharing them across threads as of that release.

2) You can update your code for registering the client as a service to do something like the following:
```swift
services.register { container -> MongoClient in
    return try MongoClient()
}
```
This will ensure that a new`MongoClient` is associated with each thread in your application.

MongoDB itself is well equipped to handle many concurrent connections/operations so I don't expect the problem is caused by the DB.

Let me know if either of the above solutions work for you.

**Comment by danieleftodi** [comment] 2019-12-20 07:25
@kmahar 

Option Two was easiest to try, and it did the trick. 👍🏻

and can successfully run:
`wrk -c 100 -t 100 -d 300 http://localhost.local:8080/dev`

2nd Option will take a bit more time / work, as I have to update the code to support the new BSON implementation

**Comment by kmahar** [comment] 2019-12-20 16:35
@danieleftodi I am glad to hear it! I am going to close this issue as it seems your problem is resolved, but feel free to open others if you run into anything else.

**Closed by kmahar** 2019-12-20 16:35 UTC
