### ISSUE TITLE
CLibMongoC compilation fails when SPM package used in an Xcode project

### ISSUE THREAD

**Issue by shadowfacts** [mongodb/mongo-swift-driver#387] opened 2020-01-09 04:15 UTC
### Swift version

```
$ swift --version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.2.0

```

### Operating system

```
$ uname -a
Darwin sleeperservice.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

### Driver version

```
$ cat MongoTest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
{
  "object": {
    "pins": [
      {
        "package": "MongoSwift",
        "repositoryURL": "https://github.com/mongodb/mongo-swift-driver.git",
        "state": {
          "branch": "master",
          "revision": "8cc72888b860828a12bddd66beac99b693a8481a",
          "version": null
        }
      },
      {
        "package": "Nimble",
        "repositoryURL": "https://github.com/Quick/Nimble.git",
        "state": {
          "branch": null,
          "revision": "f8657642dfdec9973efc79cc68bcef43a653a2bc",
          "version": "8.0.2"
        }
      },
      {
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio",
        "state": {
          "branch": null,
          "revision": "f6487a11d80bfb9a0a0a752b7442847c7e3a8253",
          "version": "2.12.0"
        }
      }
    ]
  },
  "version": 1
}

```

### What is the version(s) of `mongod` that you are running with the driver?
```
$ mongod --version
db version v4.2.1
git version: edf6d45851c0b9ee15548f0f847df141764a317e
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

### What is your server topology?

A single MongoDB instance running locally.

### How did you install `libmongoc` and `libbson` on your system

Installed/managed by the SPM package.

### Version of `libmongoc` and `libbson`

N/A

## What is the problem? 

When adding the MongoSwift SPM packge to Xcode, MongoSwift compilation fails because Xcode is unable to build the `CLibMongoC` Objective-C module due to the following erros:

- `Only <bson/bson.h> can be included directly`
- `Only <mongoc/mongoc.h> can be included directly`

These errors are outputted for every Swift file in MongoSwift.

Cloning MongoSwift at the same version and building separately from an Xcode project with `swift build` works as expected. Cloning MongoSwift, generating an Xcode project (with `make project`), and adding that project to an Xcode Workspace also compiles successfully as expected. Only when included as an SPM package through Xcode's integration is CLibMongoC broken.

## Reproducing the bug

1. Create a new macOS app project in Xcode.
2. In the app target, under "Frameworks, Libraries, and Embedded Content", click the + button.
3. Click Add Other -> Add Package Depedency...
4. Enter `https://github.com/mongodb/mongo-swift-driver` and click Next
5. Choose the specific commit `8cc72888b860828a12bddd66beac99b693a8481a` as the package version.
6. Ensure the checkbox next to the `MongoSwift` library is checked.
7. Attempt to compile the app.
8. Observe that CLibMongoC compilation fails.

**Comment by kmahar** [comment] 2020-01-23 01:42
Hi @shadowfacts, thanks for your patience as we investigated this.

Thank you for the thorough bug report! We were indeed able to reproduce this issue.

Unfortunately, it seems that the `cSettings` we define in `Package.swift`, which are necessary for building `CLibMongoc` correctly, are not being correctly picked up on by Xcode in this case.

We've filed a Swift bug about this which you can see here: [SR-12009](https://bugs.swift.org/browse/SR-12009).

So there isn't a lot we can do at the moment, I'm afraid. Are you able to use the workaround you described for now (where you include a generated Xcode project in your workspace)?

**Comment by shadowfacts** [comment] 2020-01-23 16:08
Yes, generating an Xcode project for MongoSwift and including it a workspace works and compiles successfully.

**Comment by alazirakaclan** [comment] 2020-03-14 07:48
I can not compile MongoSwift as separate project as well. Could you please provide step by step instruction, how to do it?

**Comment by kmahar** [comment] 2020-03-16 19:53
Hi @alazirakaclan, are you trying to compile the driver from the command line or using Xcode? Can you please explain what you tried doing and what error you got?
Thanks!

**Comment by hchen113** [comment] 2020-04-20 07:48
As of mid April, the workaround I performed got it to work as mentions in the thread above.

Download and mongoswift driver and use the following commands

cd mongo-swift-driver-master
swift package generate-xcodeproj

It should generate a .xcodeproj file. Open it and build it. I'm currently using Swift 5.2 on XCode 11.4.1.

Next link the compiled project to your project by dragging that .xcodeproj in your workspace. Next link it with your project but going Targets -> Build Phases -> Linking Binary With Libraries and adding the MongoSwiftSync.framework.

Or the MongoSwift.framework if you're using the async modules.

It should build successfully from there.

**Comment by valeriomazzeo** [comment] 2020-06-03 12:19
@kmahar - it seems that since Xcode 11.5 opening the project with `open Package.swift` triggers a different set of errors.

Perhaps, updating such dependency packages to the latest `swift-tools-version` manifest can fix the issue? 

I am using `1.0.0-rc1`.

![Screenshot 2020-06-03 at 13 17 22](https://user-images.githubusercontent.com/1882080/83635698-90bce080-a59c-11ea-822b-62f47da201d4.png)

**Comment by kmahar** [comment] 2020-06-03 15:01
@valeriomazzeo As of 1.0.0-rc0 we no longer depend on `swift-bson` or `swift-mongoc` - we have a vendored copy of the driver under a target called `CLibMongoC`. So I am surprised to see those errors at all.
Testing this out myself on 11.5, I get the same errors as above:
```
Only <bson/bson.h> can be included directly
Only <mongoc/mongoc.h> can be included directly
```

So it seems like there is some stale information, perhaps you need to reset your build directory?

**Comment by eriadam** [comment] 2020-06-24 21:43
The SwiftPM team did not really seem to have reacted on the issue... I reported the bug at Apple (FB7777476).

**Comment by kmahar** [comment] 2020-06-29 23:23
Thank you @eriadam !

**Comment by sherjil** [comment] 2020-07-15 21:20
is there any work around this bug???

**Comment by kmahar** [comment] 2020-07-16 01:22
Hi @sherjil, thanks for reaching out.

Couple of options:

1. In the root directory of your project which has the driver added to your Package.swift file as shown in our README, run `swift package generate-xcodeproj`. This will generate an `.xcodeproj` you can open in Xcode which will be able to successfully build the driver.

2. As others noted above (see [this comment](https://github.com/mongodb/mongo-swift-driver/issues/387#issuecomment-616373237)), you can also separately generate an `.xcodeproj` for the driver, and then add that to an existing workspace. (As an amendment to @hchen113's comment I would suggest you check out the `1.0.0` tag of the driver and generate the project from there, rather than depending on the master branch.)

**Comment by sherjil** [comment] 2020-07-16 14:08
Thanks works great now no more Error ...

For People Developing for Mac App.

don't forget to check

TARGETS / Signing & Capabilities / App Sandbox

- [ ] Incoming Connection (Server)
- [ ] Outgoing Connection (Client)

Sample Code 

```
import Cocoa
import MongoSwiftSync

class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        do{
            let client = try MongoClient("mongodb://username:password@host:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false")
            let db = client.db("myDB")
            print(db)
            print("-----")
            
            do{
                let collection = try db.createCollection("myCollections")
                print(collection)
            }catch{
                print("Error Collection")
            }
        }catch{
            print("Error Client")
        }

        // Do any additional setup after loading the view.
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }
    
}

```
I know its not good code but it get job done for me

**Comment by kmahar** [comment] 2020-07-30 17:05
Two updates on this - 

1) We have a PR in review (#513) to remove the need for `cSettings` altogether in our `Package.swift`, so this issue should go away with our next release.

2) as of SwiftNIO's 2.20 release, NIO fails to build via the generated .xcodeproj (see https://github.com/apple/swift-nio/issues/1601). My suggested workaround for now is to add an explicit dependency on NIO < 2.20 in your `Package.swift` which will force the driver, Vapor etc. to depend on a lower version.

**Comment by kmahar** [comment] 2020-07-31 14:15
FYI a fix for the SwiftNIO issue has been released in version 2.20.2.

**Comment by piers12** [comment] 2020-08-07 18:55
Any idea when that next release will be which fixes this issue? Will this fix enable the project to be compiled from Xcode?

Thinking about using this Driver Instead of the MongoDB Driver provided by Vapor and I immediately get this error when trying to build from Xcode, which isn't the best first impression.

I have tried the work around and it produces a large amount of warnings which isn't ideal.

**Comment by kmahar** [comment] 2020-08-10 14:45
Hi all, just tagged [1.0.1](https://github.com/mongodb/mongo-swift-driver/releases/tag/v1.0.1) which brings in the fix for this issue.
I'm going to close out this issue. Please let us know if you run into any problems with the new changes.

**Closed by kmahar** 2020-08-10 14:45 UTC
