### ISSUE TITLE
Not updating Chinese unicode character correctly 

### ISSUE THREAD

**Issue by samwize** [mongodb/mongo-swift-driver#221] opened 2019-03-28 09:14 UTC
The code below tries to save the name field with Chinese characters. It will be saved as "�" on the mongo server. 

```swift
let s: Document = ["name": "你"]
let d: Document = ["$set": s]
collection?.updateOne(filter: q, update: d, options: UpdateOptions(upsert: false))
```

**Comment by kmahar** [comment] 2019-03-28 13:28
Hi there, thanks so much for the bug report!

This issue was fixed recently via #212, and the fix will be included as part of our next release. 
The problem is that we were using `String.count` rather than `String.utf8.count` to get the number of bytes in a string. 

The release should happen soon, but in the meantime one workaround available is to create the `Document` directly from JSON. For example:
```swift
let json = """
        {"name": "你"}
        """
let s = try Document(fromJSON: str)
let doc: Document = ["$set": s]
```

This will bypass the buggy string encoding. 

Sorry for the inconvenience! Please let us know if you have any questions.

**Comment by samwize** [comment] 2019-03-28 23:16
Thank you! The workaround works.

**Comment by kmahar** [comment] 2019-03-29 17:18
Glad to hear it! I'm going to close this - please feel free to open new issues in the future with any other problems you run into or suggestions you have.

**Closed by kmahar** 2019-03-29 17:18 UTC

**Comment by kmahar** [comment] 2019-04-18 21:28
FYI, we've tagged a new release including the fix for this.
